### ISSUE TITLE
Can this framework call xctool cmd?

### ISSUE THREAD

**Issue by myafer** [kareman/SwiftShell#30]
I want use this for call xctool  to build my project and then uplaod to my sever. Could you give me some suggestion or a demo for me. Thanks!

**Comment by kareman** [comment]
Sure, do you want to make a commandline application written in Swift to do this? What xctool commands do you want to run? What type of server are you uploading to?

**Comment by myafer** [comment]
Thx for your reply. I had call the xcbuild to build and package the project. Your framework is very good ! And could you me some suggestion about this [https://github.com/myafer/HHSSJJ/blob/master/HHSSJJ/main.swift](https://github.com/myafer/HHSSJJ/blob/master/HHSSJJ/main.swift)

**Comment by kareman** [comment]
Okay, I have some comments:

- use `main.currentdirectory = projectPath`. This way you don't have to do `"cd " + projectPath + ";` all the time.
-  instead of using bash, call the command directly, like this: `try runAndPrint("xcodebuild", "archive", "-scheme", "TTTT", "-configuration", "Release", "-archivePath", archivepath)`. This way you don't have to remember to use \". All the arguments are sent directly to `xcodebuild` exactly the way you write them, even if they contain '*' or '?'.
-  instead of "CommandLine.arguments" you can use "main.arguments"; it contains just the arguments to the script, the first item is not the path of the script as it is with "CommandLine.arguments".

**Comment by myafer** [comment]
OK， thank you very much!
