### ISSUE TITLE
Not support `Pod` command

### ISSUE THREAD

**Issue by josercc** [kareman/SwiftShell#80]
which pod
```
/usr/local/bin/pod
```

run("/usr/local/bin/pod", "--version")  error

**Comment by kareman** [comment]
This is most likely because the environment is different in your Terminal and your Swift application. Try running the command “`env`” both in the terminal and the Swift application. See if there is anything missing in the output from the Swift application that the `pod` command might need. 

You can change the environment in SwiftShell by changing the `main.env["PATH"]` dictionary.

**Comment by josercc** [comment]
Ok thanks

**Comment by josercc** [comment]
@kareman
When I compared `main.env` and the terminal, the value of` PATH` was really different.
`print (main.env [" PATH "])`
`/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/ bin:/bin:/usr/sbin:/sbin`
When I execute `ENV` in the terminal, the following path is printed
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin`
When I execute `pod --version` using the terminal's` PATH`, the version can be successfully printed. I want to write a program for others to use, but I can't get the terminal's `PATH` path to set it, so that the commands inside can't be executed? How to solve this?

**Comment by josercc** [comment]
@kareman 
Can you add `/usr/local/bin` to` PATH` in the framework. This problem may be encountered by many people, adding will solve many people's questions.

**Comment by kareman** [comment]
I’m glad you got it working. I cannot set any environment variables in the framework, because they need to be inherited from the environment in which the application is running. So if you make a commandline application using SwiftShell, and run it from the terminal, it needs to only use the environment that the terminal currently has.
